# SLF4J SimpleLogger 設定
# --vv 3 未満の場合は Apache CXF 等のライブラリ INFO ログを出力しないよう、デフォルトレベルを warn に設定します。
org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.log.org.apache.cxf=warn
org.slf4j.simpleLogger.log.org.apache.http=warn
org.slf4j.simpleLogger.log.io.cloudsoft=warn
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false
